version: '3.2'

services:

  ruby_gem:
    build:
      context: .
      dockerfile: roro/containers/ruby_image/Dockerfile
    environment:
      - RUBY_IMAGE=${RUBY_IMAGE}
    volumes:
      - gem_cache:/gems

volumes:
  gem_cache: